from env import *

KEY_TOKEN_AUTH = KEY_TOKEN_AUTH_env
SECRET_KEY = SECRET_KEY_env
MYSQL_DB = MYSQL_DB_env
MYSQL_PASSWORD = MYSQL_PASSWORD_env
MYSQL_PORT = MYSQL_PORT_env
MYSQL_USER = MYSQL_USER_env
MYSQL_PORT = MYSQL_PORT_env
MYSQL_HOST = MYSQL_HOST_env

# mailconfig

PROVEEDOR_MAIL = ''
CORREO_MAIL = ''
PASSWORD_MAIL = ''

# DropBox Config

ACCESS_TOKEN = TOKEN_DROPBOX_env